modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Team-Hollow/Deeper-Caverns/issues"

[[mods]]
modId="deepercaverns"
version="0.0.1"
displayName="Deeper Caverns"
displayURL="http://example.com/"
authors="TODO"
description='''A nether expansion.'''

[[dependencies.deepercaverns]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deepercaverns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"
