modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Team-Hollow/Deeper-Caverns/issues"

[[mods]]
modId="deepercaverns"
version="0.0.1-alpha"
displayName="Deeper Caverns"
displayURL="https://github.com/Team-Hollow/Deeper-Caverns"
authors="bl4ckscor3 (Code), Cipher Zero X (Idea, Models), Endergized (Textures), Lachney (Sounds), Mahtaran (Idea, Code), Vamacheron (Lead)"
description='''A Nether expansion.'''

[[dependencies.deepercaverns]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deepercaverns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"
